{ pkgs, lib, ... }:

{
  programs.zsh = {
    enable = true;
    enableCompletion = true;
    autosuggestion.enable = true;
    syntaxHighlighting.enable = true;

    history = {
      size = 50000;
      save = 50000;
      ignoreDups = true;
      share = true;
    };

    oh-my-zsh = {
      enable = true;
      theme = "robbyrussell";
      plugins = [
        "git"
        "gitfast"
        "dotenv"
        "docker"
        "docker-compose"
        "colored-man-pages"
        # "mise" intentionally omitted: the OMZ mise plugin just runs
        # `eval "$(mise activate zsh)"`, which programs.mise.enableZshIntegration
        # already does — including it double-activated mise (~20ms/shell wasted).
      ];

      # Source the user's tracked custom *.zsh files (e.g. git-resign) the same
      # way the old ~/.oh-my-zsh/custom/ did. HM's oh-my-zsh uses its own $ZSH
      # in the Nix store, so the old ~/.oh-my-zsh/custom/ is no longer read —
      # these live in the repo now. ZSH_CUSTOM points here; OMZ sources
      # $ZSH_CUSTOM/*.zsh at startup.
      custom = "${../zsh/custom}";
    };

    # Anything that used to live at the bottom of the hand-written .zshrc
    # belongs here. The `mise activate` line is dropped because programs.mise
    # already wires it up declaratively.
    initContent = lib.mkAfter ''
      # Visual hint that you're inside this managed environment. On personal
      # machines just [ilia]; on shared machines (bootstrapped with
      # `install.sh --user`, which drops the marker file below) include the
      # short hostname so shells on different boxes are distinguishable:
      # [ilia@pipeline].
      if [ -f "$HOME/.config/nix-dotfiles/shared-machine" ]; then
        PROMPT="%F{cyan}[%n@%m]%f $PROMPT"
      else
        PROMPT="%F{cyan}[ilia]%f $PROMPT"
      fi

      # On musl-based hosts (Alpine, Void, ...) tell mise to prefer musl-built
      # binaries when a registry provides both variants. Without this, mise
      # falls back to glibc URLs and downloads binaries that can't run on
      # Alpine. Recognised by mise ≥ 2026.4.23; ignored by older versions.
      # See https://github.com/jdx/mise CHANGELOG for "Global libc setting".
      if command -v ldd >/dev/null 2>&1 && ldd --version 2>&1 | grep -qi musl; then
        export MISE_LIBC=musl
      fi

      # Secrets stay out of the Nix store. secrets.sops.zsh is generated by
      # `nix-secrets sync` from the tracked, sops-encrypted secrets/env.yaml
      # (modules/secrets.nix). secrets.zsh is hand-written, untracked and
      # machine-local (chmod 600); it loads second so it can override.
      [[ -r "$HOME/.config/zsh/secrets.sops.zsh" ]] && source "$HOME/.config/zsh/secrets.sops.zsh"
      [[ -r "$HOME/.config/zsh/secrets.zsh" ]] && source "$HOME/.config/zsh/secrets.zsh"
    '';
  };

  # fzf integration replaces the manual `source <(fzf --zsh)` line.
  programs.fzf = {
    enable = true;
    enableZshIntegration = true;
    defaultCommand = "fd --type f --hidden --follow --exclude .git";
  };
}
